version: "3.9"

services:
  task-manager:
    build:
      context: .
      dockerfile: build/Dockerfile-server_test
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DB_ADDR=mysql
      - DB_PORT=3306
      - DB_USER=mysql
      - DB_PWD=mysql
      - DB_NAME=tasks
      - RMQ_ADDR=rabbitmq
      - RMQ_VHOST=tasks
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./:/app/report/
    networks:
      - dev

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_HOST=mysql
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_USER=mysql
      - MYSQL_DATABASE=tasks
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'mysql --database=$$MYSQL_DATABASE --password=$$MYSQL_PASSWORD --execute="SELECT count(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B'
        ]
      interval: 30s
      timeout: 10s
      retries: 4
    networks:
      - dev
    logging:
      driver: none

  rabbitmq:
    image: rabbitmq:3
    ports:
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_VHOST=tasks
    networks:
      - dev
    logging:
      driver: none

networks:
  dev:
    driver: bridge
